# Generated by Django 5.0.7 on 2024-08-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.CharField(max_length=100),
        ),
    ]
