# Generated by Django 5.0.7 on 2024-08-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_alter_contact_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="desc",
            field=models.TextField(default="Default description"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
